config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  
  root 'pages#welcome'

  get 'auth/spotify', to: 'pages#auth'
  get 'auth/spotify/callback', to: 'pages#home'
  get 'home', to: 'pages#home'
  get 'search_result', to: 'artists#search_result'
  get 'create_discography/:id', to: 'artists#create_discography', as: 'create_discography'
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/artists_controller.rb
class ArtistsController < ApplicationController
  include ArtistsHelper
  include PagesHelper
  
  def search_result
    @found_artists_by_name = search_artists(params['search']['query'])
  end

  def create_discography
    artist = get_artist(artist_id)
    tracks = get_all_tracks_by_artist(artist)

    playlist_name = create_playlist(user_id, tracks, artist.name)

    redirect_to home_path(), flash: { success: "#{playlist_name} created!" }
  end

  private

  def artist_id
    params[:id]
  end

  def user_id
    session[:user_id]
  end
end

app/controllers/concerns/artists_helper.rb
require 'rest-client'
module ArtistsHelper
  @track_names
  def search_artists(query)
    RSpotify::Artist.search(query)
  end

  def get_artist(id)
    RSpotify::Artist.find(id)
  end

  def create_playlist(id, tracks, artist_name)
    user = RSpotify::User.new({
      'id' => id,
      'credentials' => {
        'token' => session[:access_token],
        'access_token' => session[:refresh_token],
        'access_refresh_callback' => Proc.new {}
      }
    })

    playlist = user.create_playlist!("Discography - #{artist_name}")
    playlist.add_tracks!(tracks)
    playlist.name
  end

  def get_all_tracks_by_artist(artist)
    tracks = []
    artist.albums(album_type: 'album,single').each do |album|
      tracks += album.tracks
    end
    tracks.uniq { |track| track.name }
  end
end

app/controllers/concerns/pages_helper.rb
require 'rest-client'
module PagesHelper
  def get_user(access_token)
    url = 'https://api.spotify.com/v1/me'
    res = RestClient.get(url, {authorization: "Bearer #{access_token}"})

    return JSON.parse(res.body)
  end

  def get_access_refresh_token
    uri = URI('https://accounts.spotify.com/api/token')
    prm = {
      'grant_type' => 'authorization_code',
      'code' => params['code'],
      'redirect_uri' => root_url + 'auth/spotify/callback',
      'client_id' => SPOTIFY_CLIENT_ID,
      'client_secret' => SPOTIFY_CLIENT_SECRET
    }
    res = Net::HTTP.post_form(uri, prm)
    return JSON.parse(res.body)
  end

  def refresh_access_token
    url = 'https://accounts.spotify.com/api/token'
    body = {
      'grant_type' => 'refresh_token',
      'refresh_token' => session[:refresh_token]
    }
    auth_str = Base64.strict_encode64(SPOTIFY_CLIENT_ID + ':' + SPOTIFY_CLIENT_SECRET)
    header = {
      authorization: "Basic #{auth_str}"
    }
    # body instead of body.to_json here because content-type is urlencoded
    res = RestClient.post(url, body, header)
    session[:access_token] = JSON.parse(res.body)['access_token']
  end


end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  before_action :require_login, only: :home

  def welcome; end

  def home
    if session[:access_token].nil?
      tokens = helpers.get_access_refresh_token
      session[:access_token]  = tokens['access_token']
      session[:refresh_token] = tokens['refresh_token']
      session[:expire]        = Time.now
    end

    user_response = helpers.get_user(session[:access_token])
    session[:user_id] = user_response['id']
    @name             = user_response['display_name']
  end

  def auth
    url = 'https://accounts.spotify.com/authorize'
    params = {
      'client_id' => SPOTIFY_CLIENT_ID,
      'response_type' => 'code',
      'redirect_uri' => root_url + 'auth/spotify/callback',
      'scope' => 'playlist-modify-public playlist-modify-private user-follow-read'
    }
    redirect_to "#{url}?#{params.to_query}"
  end

  private

  def require_login
    if session[:user_id].nil? && params['code'].nil?
      redirect_to action: :welcome
    elsif session[:expire] && Time.now - Time.parse(session[:expire]) > 3300
      helpers.refresh_access_token
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/artists/search_result.html.erb
<div class="list-group">
<% @found_artists_by_name.each do |a| %>
  <div class="list-group-item">
    <%= link_to create_discography_path(a.id), method: :get do %>
      <%= a.name %>
    <% end %>
  </div>
<% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Spotify Discography Generator</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta content="IE=edge,chrome=1" http-equiv="X-UA-Compatible">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  
  <body class="container-fluid p-0 bg-light">
    <div class="navbar navbar-expand-lg navbar-light" style="background-color: white">
      <%= link_to root_path(), class: "navbar-brand" do %>
            Spotify Discography Generator
      <% end %>

      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item">
            <a href="" class="nav-item nav-link active">View source on GitHub</a>
          </li>
        </ul>
      </div>
    </div>
  
    <div class="row">
      <div class="col-lg-2 col-1"></div>
      <div class="col-lg-8 col-10">
        <%= yield %>
      </div>
      <div class="col-lg-2 col-1"></div>
    </div>
  </body>
</html>

app/views/pages/home.html.erb
<div class="container">

<div class="card">
  <div class="row no-gutters">
      <div class="card-body">
        <h5 class="card-title">Welcome <span class="font-weight-bold"><%= @name %></span></h5>
      </div>
  </div>
</div>

<h2>How it works</h2>
<p>Search for your favorite artist below and click on the artist name. Check your Spotify library to see the playlist as "Discography - #artist-name"</p>

<% if flash[:success] %>
  <div class="alert alert-success">
    <%= flash[:success] %>
  </div>
<% end %>

<%= form_for :search, url: search_result_path(), method: :get do |f| %>
  <div class="field">
    <%= f.text_field :query, placeholder: 'Search artist', class: 'form-control' %>
  </div>
  <div class="actions">
    <%= f.submit :Search, class: 'btn btn-primary' %>
  </div>
<% end %>

</div>

app/views/pages/welcome.html.erb
<div class="">
  <h1>Welcome to spotify discography playlist generator</h1>

  <p>Generate a playlist with every song by an artist. Sign in to your spotify account below to begin</p>

  <%= link_to 'Sign in to Spotify', '/auth/spotify' %>

</div>